server.port: ${PORT:0}
spring:
  application:
    name: emoji-ws
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client.serviceUrl.defaultZone: http://localhost:8010/eureka
  instance.instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


