server.port: ${PORT:0}

spring:
  application:
    name: user-ws
  datasource:
    url: jdbc:mysql://localhost:3306/fruits?serverTimezone=UTC
    username: admin
    password: admin
  jpa:
    hibernate.ddl-auto: validate
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  zipkin:
    base-url: http://localhost:9411/
    sender.type: web
  sleuth.sampler.probability: 1

eureka:
  client.serviceUrl.defaultZone: http://localhost:8010/eureka
  instance.instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

jwt:
  secret: hfgry463hf746hf573ydh475fhy5739
  expiration: 600000

login.url.path: /api/v1/users/login

logging.level.org.springframework.web: TRACE


